import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import './styles.css'

const api=async(path,token,options={})=>{const response=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||`Request failed (${response.status})`);return data}
const decodeToken=token=>{try{return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return null}}
const badge=value=><span className={`badge ${value}`}>{String(value).replaceAll('_',' ')}</span>

function Login({onLogin}){const[token,setToken]=useState('');return <main className="login"><section className="login-card"><div className="brand-mark">FC</div><p className="eyebrow">Secure operations portal</p><h1>Financial Crime<br/>Compliance Platform</h1><p className="muted">Authenticate with an identity-provider JWT to enter the analyst workspace.</p><label>Access token<textarea value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste bearer JWT"/></label><button onClick={()=>onLogin(token)} disabled={!token.trim()}>Continue securely</button><p className="fine">Tokens remain in this browser session and are never embedded in the frontend bundle.</p></section></main>}

function App(){const[token,setToken]=useState(()=>sessionStorage.getItem('fccp_token')||'');const claims=useMemo(()=>decodeToken(token),[token]);const[view,setView]=useState('dashboard');const[customers,setCustomers]=useState([]);const[alerts,setAlerts]=useState([]);const[error,setError]=useState('');const[loading,setLoading]=useState(false);
const login=value=>{if(!decodeToken(value)){setError('Token is not a valid JWT');return}sessionStorage.setItem('fccp_token',value);setToken(value);setError('')};const logout=()=>{sessionStorage.removeItem('fccp_token');setToken('')};
const load=async()=>{if(!token)return;setLoading(true);setError('');try{const[c,a]=await Promise.all([api('/v1/customers?page_size=100',token),api('/v1/alerts?page_size=100',token)]);setCustomers(c.items||[]);setAlerts(a.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[token]);if(!token||!claims)return <><Login onLogin={login}/>{error&&<div className="toast">{error}</div>}</>;
const pending=customers.filter(c=>c.status==='pending_approval');const openAlerts=alerts.filter(a=>a.status==='open');const nav=[['dashboard','Overview'],['customers','Customers'],['approvals',`Approvals ${pending.length}`],['alerts',`Alerts ${openAlerts.length}`]];
return <div className="shell"><aside><div className="brand"><div className="brand-mark small">FC</div><div><strong>Northstar</strong><span>Compliance OS</span></div></div><nav>{nav.map(([id,label])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}>{label}</button>)}</nav><div className="profile"><div className="avatar">{claims.sub?.[0]?.toUpperCase()}</div><div><strong>{claims.sub}</strong><span>{claims.role}</span></div><button onClick={logout}>↗</button></div></aside><main className="workspace"><header><div><p className="eyebrow">Operations / {view}</p><h1>{view[0].toUpperCase()+view.slice(1)}</h1></div><div className="header-actions"><span className="live">● Systems operational</span><button className="secondary" onClick={load}>Refresh</button></div></header>{error&&<div className="error">{error}</div>}{loading?<div className="loading">Loading verified compliance data…</div>:<Content view={view} customers={customers} alerts={alerts} token={token} reload={load}/>}</main></div>}

function Content({view,customers,alerts,token,reload}){if(view==='dashboard')return <Dashboard customers={customers} alerts={alerts}/>;if(view==='customers')return <Customers items={customers}/>;if(view==='approvals')return <Approvals items={customers.filter(c=>c.status==='pending_approval')} token={token} reload={reload}/>;return <Alerts items={alerts} token={token} reload={reload}/>}
function Dashboard({customers,alerts}){const cards=[['Total customers',customers.length,'All monitored entities'],['Pending approval',customers.filter(c=>c.status==='pending_approval').length,'Requires independent review'],['Open alerts',alerts.filter(a=>a.status==='open').length,'Investigation queue'],['High severity',alerts.filter(a=>a.status==='open'&&a.severity==='high').length,'Immediate attention']];return <><section className="metrics">{cards.map(([l,v,s])=><article><span>{l}</span><strong>{v}</strong><small>{s}</small></article>)}</section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Live queue</p><h2>Recent monitoring alerts</h2></div></div><AlertTable items={alerts.slice(0,6)}/></section></>}
function Customers({items}){return <section className="panel"><div className="panel-title"><div><p className="eyebrow">Customer lifecycle</p><h2>Risk-rated entities</h2></div><span>{items.length} records</span></div><table><thead><tr><th>Customer</th><th>Country</th><th>Risk</th><th>Due diligence</th><th>Status</th><th>Created</th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td><strong>{c.legal_name}</strong><small>{c.external_ref||c.id.slice(0,8)}</small></td><td>{c.country_code}</td><td>{badge(c.risk_assessment.rating)}</td><td>{c.risk_assessment.due_diligence.replaceAll('_',' ')}</td><td>{badge(c.status)}</td><td>{new Date(c.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></section>}
function Approvals({items,token,reload}){const act=async(id,decision)=>{const reason=prompt(`Reason for ${decision}`);if(reason===null)return;await api(`/v1/customers/${id}/${decision}`,token,{method:'POST',body:JSON.stringify({reason})});reload()};return <section className="panel"><div className="panel-title"><div><p className="eyebrow">Maker-checker</p><h2>Independent review queue</h2></div></div>{items.length===0?<Empty text="No customers awaiting approval"/>:<div className="cards">{items.map(c=><article className="review-card"><div><h3>{c.legal_name}</h3><p>{c.country_code} · score {c.risk_assessment.score} · submitted by {c.created_by}</p></div><div>{badge(c.risk_assessment.rating)}<button onClick={()=>act(c.id,'approve')}>Approve</button><button className="danger" onClick={()=>act(c.id,'reject')}>Reject</button></div></article>)}</div>}</section>}
function Alerts({items,token,reload}){const close=async id=>{const reason=prompt('Document the investigation outcome');if(!reason)return;await api(`/v1/alerts/${id}/close`,token,{method:'POST',body:JSON.stringify({reason})});reload()};return <section className="panel"><div className="panel-title"><div><p className="eyebrow">Explainable monitoring</p><h2>Alert investigation queue</h2></div></div><AlertTable items={items} onClose={close}/></section>}
function AlertTable({items,onClose}){return items.length===0?<Empty text="No monitoring alerts"/>:<table><thead><tr><th>Rule</th><th>Reason</th><th>Severity</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>{items.map(a=><tr key={a.id}><td><strong>{a.rule_code.replaceAll('_',' ')}</strong><small>{a.rule_version}</small></td><td>{a.description}</td><td>{badge(a.severity)}</td><td>{badge(a.status)}</td><td>{new Date(a.created_at).toLocaleString()}</td><td>{onClose&&a.status==='open'&&<button className="compact" onClick={()=>onClose(a.id)}>Close</button>}</td></tr>)}</tbody></table>}
const Empty=({text})=><div className="empty"><span>✓</span><h3>{text}</h3><p>The operational queue is clear.</p></div>
createRoot(document.getElementById('root')).render(<App/>)
